spring:
  application:
    name: organisation-service
  profile:
    active:
      default
  cloud:
    config:
      enable: true

eurkea:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/